baseURL = "https://blog.10oz.tw"
languageCode = "en-us"
title = "XiaoXiao Notes"
publishDir = "docs"

theme = "hugo-theme-m10c"
paginate = 10
[params]
  author = "Xiao Xiao"
  description = "XiaoXiao 的筆記書"

