baseURL = "https://blog.10oz.tw"
languageCode = "en-us"
title = "XiaoXiao Notes"
publishDir = "docs"

theme = "m10c-plus"
paginate = 10
paginatePath = "pages"

sectionPagesMenu = "main"
[menu]
  [[menu.main]]
    name = "用 Tags 分類"
    url = "/tags"
  [[menu.main]]
    name = "關於 XiaoXiao"
    url = "/about"
  [[menu.main]]
    name = "回到文章列表"
    url = "/"

[params]
  author = "Xiao Xiao"
  description = "XiaoXiao 的筆記書"
  [[params.social]]
    name = "github"
    url = "https://github.com/XiaoXiaoSN"

  [params.style]
    profileBackground = "#333333"
    profileFontColor = "#f5e3e0"
    profileTitleColor = "#f5f5f5"
    contentBackground = "#fafafa"
    contentFontColor = "#212121"
    contentTitleColor = "#111111"
    codeBackground = "#efefef"
    primaryColor = "#0366d6"

[markup.highlight]
  style = "friendly"

[blackfriday]
  extensions = ["hardLineBreak"]
